#!/bin/bash
#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -G 1
#SBATCH -q regular
#SBATCH -t 00:15:00
#SBATCH -A m4341

./graph_cuda -f ../datasets/roadNet-CA.txt -a gpu-bellman-ford -s 0 -o gpu-bellman-ford.txt